CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(255) NOT NULL,
    receiver VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    time_received DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    time_deleted DATETIME DEFAULT NULL
);
